#!/bin/bash

FIREFOX_VERSION=$( firefox -version | cut -d " " -f 3 )

echo "
{
  \"capabilities\": [
    {
      \"version\": \"$FIREFOX_VERSION\",
      \"browserName\": \"firefox\",
      \"maxInstances\": $NODE_MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    }
  ],
  \"proxy\": \"org.openqa.grid.selenium.proxy.DefaultRemoteProxy\",
  \"maxSession\": $NODE_MAX_SESSION,
  \"port\": 5555,
  \"register\": true,
  \"registerCycle\": $NODE_REGISTER_CYCLE
}" 

