apiVersion: v2
name: selenium-grid
description: A Helm chart for creating a Selenium Grid Server in Kubernetes
type: application
version: 0.55.0
appVersion: 4.44.0-20260505
icon: https://github.com/SeleniumHQ/docker-selenium/raw/trunk/logo.png
dependencies:
- repository: https://kedacore.github.io/charts
  version: ^2.20.0
  name: keda
  condition: autoscaling.enabled, keda.enabled
- repository: https://traefik.github.io/charts
  version: ^41.0.0
  name: traefik
  condition: ingress.enableWithController, traefik.enabled
- repository: https://jaegertracing.github.io/helm-charts
  version: ^4.0.0
  name: jaeger
  condition: tracing.enabled, jaeger.enabled
- repository: https://prometheus-community.github.io/helm-charts
  version: ^87.0.0
  name: kube-prometheus-stack
  condition: monitoring.enabled, kube-prometheus-stack.enabled
- repository: https://cloudpirates-io.github.io/helm-charts
  version: ^0.19.0
  name: postgres
  alias: postgresql
  condition: postgresql.enabled
- repository: https://cloudpirates-io.github.io/helm-charts
  version: ^0.30.0
  name: redis
  condition: redis.enabled
maintainers:
  - name: SeleniumHQ
    email: docker-selenium@seleniumhq.org
    url: https://github.com/SeleniumHQ
sources:
  - https://github.com/SeleniumHQ/docker-selenium
