ingress:
  enabled: false

dynamicGrid:
  enabled: true
  defaults:
    imageTag: 4.43.0-20260404
    nodeSessionTimeout: "600"
    config:
      kubernetes:
        assetsPath: /opt/selenium/assets
        terminationGracePeriod: "30"

chromeNode:
  imageName: node-chromium
  nodeMaxSessions: 20

firefoxNode:
  nodeMaxSessions: 20

edgeNode:
  enabled: false
