#!/usr/bin/env bash
export NODE_LOG="/tmp/sel-node.log"

ADDR=localhost
PORT=4444

if [ -n "$HUB_PORT_4444_TCP_ADDR" ]; then
	ADDR=$HUB_PORT_4444_TCP_ADDR
fi

if [ -n "$HUB_PORT_4444_TCP_PORT" ]; then
	PORT=$HUB_PORT_4444_TCP_PORT
fi

sudo -E -i -u seluser \
  java -jar /opt/selenium/selenium-server-standalone.jar \
    -role node \
    -hub http://$ADDR:$PORT/grid/register \
		-nodeConfig /opt/selenium/config.json
    -Dwebdriver.chrome.args="--no-sandbox" \
    -Dselenium.chrome.args="--no-sandbox" \
    | tee $NODE_LOG
