#!/bin/bash

echo "
{
  \"capabilities\": [
    {
      \"browserName\": \"chrome\",
      \"maxInstances\": $NODE_MAX_INSTANCES,
      \"seleniumProtocol\": \"WebDriver\"
    }
  ],
  \"proxy\": \"org.openqa.grid.selenium.proxy.DefaultRemoteProxy\",
  \"maxSession\": $NODE_MAX_SESSION,
  \"port\": $NODE_PORT,
  \"register\": true,
  \"registerCycle\": $NODE_REGISTER_CYCLE
}" 

