# To execute this docker compose yml file use `docker compose -f docker-compose-v3-dev.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-dev.yml down`
version: "3"
services:
  chrome:
    image: selenium/node-chrome:4.23.1-20240820
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  edge:
    image: selenium/node-edge:4.23.1-20240820
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:129.0.1-20240820
    shm_size: 2gb
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  selenium-hub:
    image: selenium/hub:4.23.1-20240820
    container_name: selenium-hub
    volumes:
      - ./selenium_server_deploy.jar:/opt/selenium/selenium-server.jar
    ports:
      - "4442:4442"
      - "4443:4443"
      - "4444:4444"
