# To execute this docker compose yml file use `docker compose -f docker-compose-v3-full-grid-secure.yml up`
# Add the `-d` flag at the end for detached execution
# To stop the execution, hit Ctrl+C, and then `docker compose -f docker-compose-v3-full-grid-secure.yml down`
version: "3"
services:
  selenium-event-bus:
    image: selenium/event-bus:4.25.0-20240922
    container_name: selenium-event-bus
    ports:
      - "4442:4442"
      - "4443:4443"
      - "5557:5557"
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_ENABLE_TLS=true

  selenium-sessions:
    image: selenium/sessions:4.25.0-20240922
    container_name: selenium-sessions
    ports:
      - "5556:5556"
    depends_on:
      - selenium-event-bus
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TLS=true

  selenium-session-queue:
    image: selenium/session-queue:4.25.0-20240922
    container_name: selenium-session-queue
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    ports:
      - "5559:5559"
    environment:
      - SE_ENABLE_TLS=true

  selenium-distributor:
    image: selenium/distributor:4.25.0-20240922
    container_name: selenium-distributor
    ports:
      - "5553:5553"
    depends_on:
      - selenium-event-bus
      - selenium-sessions
      - selenium-session-queue
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
      - SE_ENABLE_TLS=true

  selenium-router:
    image: selenium/router:4.25.0-20240922
    container_name: selenium-router
    ports:
      - "4444:4444"
    depends_on:
      - selenium-distributor
      - selenium-sessions
      - selenium-session-queue
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_DISTRIBUTOR_HOST=selenium-distributor
      - SE_DISTRIBUTOR_PORT=5553
      - SE_SESSIONS_MAP_HOST=selenium-sessions
      - SE_SESSIONS_MAP_PORT=5556
      - SE_SESSION_QUEUE_HOST=selenium-session-queue
      - SE_SESSION_QUEUE_PORT=5559
      - SE_ENABLE_TLS=true

  chrome:
    image: selenium/node-chrome:4.25.0-20240922
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TLS=true
      - SE_NODE_GRID_URL=https://localhost:4444
      - SE_SERVER_PROTOCOL=https

  edge:
    image: selenium/node-edge:4.25.0-20240922
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TLS=true
      - SE_NODE_GRID_URL=https://localhost:4444
      - SE_SERVER_PROTOCOL=https

  firefox:
    image: selenium/node-firefox:130.0.1-20240922
    shm_size: 2gb
    depends_on:
      - selenium-event-bus
    volumes:
      - ./charts/selenium-grid/certs:/opt/selenium/secrets
    environment:
      - SE_EVENT_BUS_HOST=selenium-event-bus
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_ENABLE_TLS=true
      - SE_NODE_GRID_URL=https://localhost:4444
      - SE_SERVER_PROTOCOL=https
