FROM selenium/node-base:2.45.0
MAINTAINER Selenium <selenium-developers@googlegroups.com>

USER root

#========================
# Selenium Configuration
#========================
COPY config.json /opt/selenium/config.json
