{{- if and (eq (include "seleniumGrid.useKEDA" $) "true") $.Values.autoscaling.patchObjectFinalizers.enabled }}
apiVersion: batch/v1
kind: Job
metadata:
  name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
  namespace: {{ .Release.Namespace }}
  {{- with $.Values.autoscaling.patchObjectFinalizers.annotations }}
  annotations: &patch_objects_job_annotations
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels: &patch_objects_job_labels
    app: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
    app.kubernetes.io/name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
  {{- with $.Values.customLabels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  template:
    metadata:
      {{- with $.Values.autoscaling.patchObjectFinalizers.annotations }}
      annotations: *patch_objects_job_annotations
      {{- end }}
      labels: *patch_objects_job_labels
      name: {{ template "seleniumGrid.keda.patchObjectsJob.fullname" $ }}
    spec:
      activeDeadlineSeconds: {{ $.Values.autoscaling.patchObjectFinalizers.activeDeadlineSeconds }}
      serviceAccountName: {{ default (include "seleniumGrid.serviceAccount.fullname" $) $.Values.autoscaling.patchObjectFinalizers.serviceAccount }}
      serviceAccount: {{ default (include "seleniumGrid.serviceAccount.fullname" $) $.Values.autoscaling.patchObjectFinalizers.serviceAccount }}
      containers:
        - name: kubectl
          image: {{ $.Values.global.seleniumGrid.kubectlImage }}
          command: ["/bin/sh", "-c"]
          args:
            - |
              echo "Cleaning up ScaledObjects, ScaledJobs and HPAs for {{ .Release.Name }} when upgrading or disabling autoscaling."
              kubectl get ScaledObjects,ScaledJobs,TriggerAuthentication -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} -o=json | jq '.metadata.finalizers = null' | kubectl apply -f - || true ;
              kubectl delete ScaledObjects,ScaledJobs,TriggerAuthentication -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} --wait || true ;
              kubectl delete hpa -n {{ .Release.Namespace }} -l component.autoscaling={{ .Release.Name }} --wait || true ;
        {{- with $.Values.autoscaling.patchObjectFinalizers.resources }}
          resources: {{ toYaml . | nindent 12 }}
        {{- end }}
    {{- if or $.Values.global.seleniumGrid.imagePullSecret $.Values.autoscaling.patchObjectFinalizers.imagePullSecret }}
      imagePullSecrets:
        - name: {{ default $.Values.global.seleniumGrid.imagePullSecret $.Values.autoscaling.patchObjectFinalizers.imagePullSecret }}
    {{- end }}
      restartPolicy: Never
{{- end }}
