USER seluser

#====================================
# Scripts to run Vaadin Testbench Standalone
#====================================
COPY start-testbench-standalone.sh /opt/bin/start-testbench-standalone.sh

#==============================
# Supervisor configuration file
#==============================
COPY selenium.conf /etc/supervisor/conf.d/


EXPOSE 4444
