USER 1200

#========================
# Selenium SessionQueuer Configuration
#========================

EXPOSE 5559

COPY start-selenium-grid-sessionqueuer.sh \
    /opt/bin/

COPY selenium-grid-sessionqueuer.conf /etc/supervisor/conf.d/
