USER 1200

#========================
# Selenium SessionQueuer Configuration
#========================

EXPOSE 5559

COPY start-selenium-grid-session-queuer.sh \
    /opt/bin/

COPY selenium-grid-session-queuer.conf /etc/supervisor/conf.d/
