{{- if .Values.dynamicGrid.enabled }}
{{- range $browser := list "chrome" "firefox" "edge" }}
{{- $baseNode := get $.Values (printf "%sNode" $browser) }}
{{- range $i, $newNode := get $.Values.crossBrowsers (printf "%sNode" $browser) }}
{{- $nodeConfig := merge $newNode $baseNode -}}
{{- if $nodeConfig.enabled }}
{{- $name := include "seleniumGrid.dynamicGrid.browserNode.fullname" (dict "browser" $browser "node" $nodeConfig "root" $) }}
{{- $configMapName := include "seleniumGrid.dynamicGrid.browserNode.configmap.fullname" (dict "browser" $browser "node" $nodeConfig "root" $) }}
{{- $nodeImageRegistry := default (default $.Values.global.seleniumGrid.imageRegistry $.Values.dynamicGrid.defaults.imageRegistry) $nodeConfig.imageRegistry }}
{{- $nodeImageTag := default (default $.Values.global.seleniumGrid.nodesImageTag $.Values.dynamicGrid.defaults.imageTag) $nodeConfig.imageTag }}
{{- $imagePullSecret := default $.Values.global.seleniumGrid.imagePullSecret $nodeConfig.imagePullSecret }}
{{- $nodeMaxSessions := default $.Values.global.seleniumGrid.nodeMaxSessions $nodeConfig.nodeMaxSessions | int64 }}
{{- $nodeEnableManagedDownloads := default $.Values.global.seleniumGrid.nodeEnableManagedDownloads $nodeConfig.nodeEnableManagedDownloads }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- with $nodeConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ $nodeConfig.replicas }}
  revisionHistoryLimit: {{ $.Values.global.seleniumGrid.revisionHistoryLimit }}
  strategy:
    {{- template "seleniumGrid.updateStrategy" (list $nodeConfig $.Values.global.seleniumGrid) }}
  selector:
    matchLabels:
      app: {{ $name }}
      app.kubernetes.io/instance: {{ $.Release.Name }}
  template:
    metadata:
      labels:
        app: {{ $name }}
        app.kubernetes.io/name: {{ $name }}
        {{- include "seleniumGrid.commonLabels" $ | nindent 8 }}
        {{- with $nodeConfig.labels }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
      annotations:
        checksum/event-bus-configmap: {{ include (print $.Template.BasePath "/event-bus-configmap.yaml") $ | sha256sum }}
        checksum/logging-configmap: {{ include (print $.Template.BasePath "/logging-configmap.yaml") $ | sha256sum }}
        checksum/server-configmap: {{ include (print $.Template.BasePath "/server-configmap.yaml") $ | sha256sum }}
        checksum/dynamic-node-config: {{ include "seleniumGrid.dynamicGrid.browser.kubernetesToml" (dict "root" $ "node" $nodeConfig) | sha256sum }}
        {{- if $.Values.secrets.create }}
        checksum/common-secrets: {{ include (print $.Template.BasePath "/secrets.yaml") $ | sha256sum }}
        {{- end }}
        {{- if $.Values.basicAuth.enabled }}
        checksum/basic-auth-secrets: {{ include (print $.Template.BasePath "/basic-auth-secret.yaml") $ | sha256sum }}
        {{- end }}
        {{- with $nodeConfig.annotations }}
          {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      serviceAccountName: {{ include "seleniumGrid.dynamicGrid.serviceAccount.fullname" $ }}
      {{- if $imagePullSecret }}
      imagePullSecrets:
        - name: {{ $imagePullSecret }}
      {{- end }}
      {{- with $nodeConfig.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- if or $.Values.global.seleniumGrid.affinity $nodeConfig.affinity }}
      affinity:
        {{- toYaml (default $.Values.global.seleniumGrid.affinity $nodeConfig.affinity) | nindent 8 }}
      {{- end }}
      {{- if or $.Values.global.seleniumGrid.topologySpreadConstraints $nodeConfig.topologySpreadConstraints }}
      {{- $topologySpreadConstraints := default $.Values.global.seleniumGrid.topologySpreadConstraints $nodeConfig.topologySpreadConstraints }}
      topologySpreadConstraints:
      {{- range $constraint := $topologySpreadConstraints }}
        - {{ toYaml $constraint | nindent 10 | trim }}
          {{- if not $constraint.labelSelector }}
          labelSelector:
            matchLabels:
              app: {{ $name }}
          {{- end }}
      {{- end }}
      {{- end }}
      {{- with $nodeConfig.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with $nodeConfig.priorityClassName }}
      priorityClassName: {{ . }}
      {{- end }}
      terminationGracePeriodSeconds: {{ $nodeConfig.terminationGracePeriodSeconds }}
      containers:
        - name: {{ $name }}
          image: {{ printf "%s/%s:%s" $nodeImageRegistry $.Values.dynamicGrid.defaults.imageName $nodeImageTag }}
          imagePullPolicy: {{ $nodeConfig.imagePullPolicy }}
          env:
            - name: SE_NODE_KUBERNETES_CONFIG_FILENAME
              value: "kubernetes.toml"
            - name: SE_OTEL_SERVICE_NAME
              value: {{ $name | quote }}
            - name: SE_OTEL_RESOURCE_ATTRIBUTES
              value: {{ include "seleniumGrid.tracing.attributes" $ | quote }}
            - name: SE_NODE_ENABLE_MANAGED_DOWNLOADS
              value: {{ $nodeEnableManagedDownloads | quote }}
            - name: SE_DYNAMIC_MAX_SESSIONS
              value: {{ $nodeMaxSessions | quote }}
          {{- if gt $nodeMaxSessions 1 }}
            - name: SE_DYNAMIC_OVERRIDE_MAX_SESSIONS
              value: "true"
          {{- end }}
          {{- with $.Values.dynamicGrid.defaults.nodeSessionTimeout }}
            - name: SE_NODE_SESSION_TIMEOUT
              value: {{ . | quote }}
          {{- end }}
          {{- with $.Values.dynamicGrid.defaults.nodeHeartbeatPeriod }}
            - name: SE_NODE_HEARTBEAT_PERIOD
              value: {{ . | quote }}
          {{- end }}
          {{- with $.Values.dynamicGrid.defaults.nodeConnectionLimitPerSession }}
            - name: SE_NODE_CONNECTION_LIMIT_PER_SESSION
              value: {{ . | quote }}
          {{- end }}
          {{- with $.Values.dynamicGrid.defaults.externalUrl }}
            - name: SE_EXTERNAL_URL
              value: {{ tpl (. | toString) $ | quote }}
          {{- end }}
          {{- with $nodeConfig.extraEnvironmentVariables }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          envFrom:
            - configMapRef:
                name: {{ template "seleniumGrid.eventBus.configmap.fullname" $ }}
            - configMapRef:
                name: {{ template "seleniumGrid.logging.configmap.fullname" $ }}
            - configMapRef:
                name: {{ template "seleniumGrid.server.configmap.fullname" $ }}
            - secretRef:
                name: {{ template "seleniumGrid.common.secrets.fullname" $ }}
          {{- if $.Values.basicAuth.enabled }}
            - secretRef:
                name: {{ template "seleniumGrid.basicAuth.secrets.fullname" $ }}
          {{- end }}
          {{- with $nodeConfig.extraEnvFrom }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          ports:
            - containerPort: {{ $nodeConfig.port }}
              protocol: TCP
          volumeMounts:
            - name: dynamic-grid-config
              mountPath: /opt/selenium/kubernetes.toml
              subPath: kubernetes.toml
              readOnly: true
          {{- if or $.Values.dynamicGrid.assets.existingClaim $.Values.dynamicGrid.assets.enabled }}
            - name: dynamic-grid-assets
              mountPath: {{ default "/opt/selenium/assets" $.Values.dynamicGrid.defaults.config.kubernetes.assetsPath }}
          {{- end }}
          {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
            - name: {{ include "seleniumGrid.tls.fullname" $ | quote }}
              mountPath: {{ $.Values.tls.certVolumeMountPath }}
              readOnly: true
          {{- end }}
          {{- with $nodeConfig.extraVolumeMounts }}
            {{- tpl (toYaml .) $ | nindent 12 }}
          {{- end }}
          {{- with $nodeConfig.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
          {{- if $nodeConfig.startupProbe.enabled }}
          startupProbe:
            httpGet:
              path: {{ $nodeConfig.startupProbe.path }}
              port: {{ $nodeConfig.port }}
              scheme: {{ include "seleniumGrid.probe.httpGet.schema" $ }}
            initialDelaySeconds: {{ $nodeConfig.startupProbe.initialDelaySeconds }}
            periodSeconds: {{ $nodeConfig.startupProbe.periodSeconds }}
            timeoutSeconds: {{ $nodeConfig.startupProbe.timeoutSeconds }}
            failureThreshold: {{ $nodeConfig.startupProbe.failureThreshold }}
            successThreshold: {{ $nodeConfig.startupProbe.successThreshold }}
          {{- end }}
          {{- if $nodeConfig.readinessProbe.enabled }}
          readinessProbe:
            httpGet:
              path: {{ $nodeConfig.readinessProbe.path }}
              port: {{ $nodeConfig.port }}
              scheme: {{ include "seleniumGrid.probe.httpGet.schema" $ }}
            initialDelaySeconds: {{ $nodeConfig.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ $nodeConfig.readinessProbe.periodSeconds }}
            timeoutSeconds: {{ $nodeConfig.readinessProbe.timeoutSeconds }}
            failureThreshold: {{ $nodeConfig.readinessProbe.failureThreshold }}
            successThreshold: {{ $nodeConfig.readinessProbe.successThreshold }}
          {{- end }}
          {{- if $nodeConfig.livenessProbe.enabled }}
          livenessProbe:
            httpGet:
              path: {{ $nodeConfig.livenessProbe.path }}
              port: {{ $nodeConfig.port }}
              scheme: {{ include "seleniumGrid.probe.httpGet.schema" $ }}
            initialDelaySeconds: {{ $nodeConfig.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ $nodeConfig.livenessProbe.periodSeconds }}
            timeoutSeconds: {{ $nodeConfig.livenessProbe.timeoutSeconds }}
            failureThreshold: {{ $nodeConfig.livenessProbe.failureThreshold }}
            successThreshold: {{ $nodeConfig.livenessProbe.successThreshold }}
          {{- end }}
      volumes:
        - name: dynamic-grid-config
          configMap:
            name: {{ $configMapName }}
        {{- if or $.Values.dynamicGrid.assets.existingClaim $.Values.dynamicGrid.assets.enabled }}
        - name: dynamic-grid-assets
          persistentVolumeClaim:
            claimName: {{ include "seleniumGrid.dynamicGrid.assets.claimName" $ }}
        {{- end }}
        {{- if eq (include "seleniumGrid.server.secureConnection" $) "true" }}
        - name: {{ include "seleniumGrid.tls.fullname" $ | quote }}
          secret:
            secretName: {{ include "seleniumGrid.tls.fullname" $ | quote }}
        {{- end }}
        {{- with $nodeConfig.extraVolumes }}
          {{- tpl (toYaml .) $ | nindent 8 }}
        {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
