{{- if .Values.dynamicGrid.enabled }}
{{- range $browser := list "chrome" "firefox" "edge" }}
{{- $baseNode := get $.Values (printf "%sNode" $browser) }}
{{- range $i, $newNode := get $.Values.crossBrowsers (printf "%sNode" $browser) }}
{{- $nodeConfig := merge $newNode $baseNode -}}
{{- if and $nodeConfig.enabled $nodeConfig.service.enabled }}
{{- $name := include "seleniumGrid.dynamicGrid.browserNode.fullname" (dict "browser" $browser "node" $nodeConfig "root" $) }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
  {{- with $nodeConfig.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ $nodeConfig.service.type }}
  selector:
    app: {{ $name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  {{- if and (eq $nodeConfig.service.type "LoadBalancer") ($nodeConfig.service.loadBalancerIP) }}
  loadBalancerIP: {{ $nodeConfig.service.loadBalancerIP }}
  {{- end }}
  ports:
    - name: web
      port: {{ $nodeConfig.port }}
      targetPort: {{ $nodeConfig.port }}
      protocol: TCP
  {{- with $nodeConfig.service.externalTrafficPolicy }}
  externalTrafficPolicy: {{ . }}
  {{- end }}
  {{- with $nodeConfig.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
