{{- if and .Values.dynamicGrid.enabled .Values.dynamicGrid.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "seleniumGrid.dynamicGrid.serviceAccount.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: selenium-dynamic-grid
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
  {{- with .Values.dynamicGrid.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
