{{- if and .Values.dynamicGrid.enabled .Values.dynamicGrid.jobTemplates }}
{{- range $name, $template := .Values.dynamicGrid.jobTemplates }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seleniumGrid.dynamicGrid.jobTemplate.fullname" (list $name $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
data:
  template: |
{{ tpl ($template | toString) $ | indent 4 }}
---
{{- end }}
{{- end }}
