{{- if .Values.dynamicGrid.enabled }}
{{- range $browser := list "chrome" "firefox" "edge" }}
{{- $baseNode := get $.Values (printf "%sNode" $browser) }}
{{- range $i, $newNode := get $.Values.crossBrowsers (printf "%sNode" $browser) }}
{{- $nodeConfig := merge $newNode $baseNode -}}
{{- if $nodeConfig.enabled }}
{{- $name := include "seleniumGrid.dynamicGrid.browserNode.fullname" (dict "browser" $browser "node" $nodeConfig "root" $) }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "seleniumGrid.dynamicGrid.browserNode.configmap.fullname" (dict "browser" $browser "node" $nodeConfig "root" $) }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}
    app.kubernetes.io/name: {{ $name }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- with $nodeConfig.labels }}
      {{- toYaml . | nindent 4 }}
    {{- end }}
data:
  kubernetes.toml: |
{{ include "seleniumGrid.dynamicGrid.browser.kubernetesToml" (dict "root" $ "node" $nodeConfig) | indent 4 }}
---
{{- end }}
{{- end }}
{{- end }}
{{- end }}
