{{- if and (eq (include "seleniumGrid.monitoring.enabled" $) "true") .Values.monitoring.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ template "seleniumGrid.monitoring.exporter.fullname" $ }}
  namespace: {{ .Values.monitoring.serviceMonitor.namespace | default .Release.Namespace }}
  {{- with .Values.monitoring.serviceMonitor.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
  labels:
    release: {{ .Release.Name }}
    {{- include "seleniumGrid.commonLabels" $ | nindent 4 }}
    {{- with .Values.monitoring.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  selector:
    matchLabels:
      {{- if $.Values.isolateComponents }}
      app: {{ template "seleniumGrid.router.fullname" $ }}
      {{- else }}
      app: {{ template "seleniumGrid.hub.fullname" $ }}
      {{- end }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  endpoints:
    - port: tcp-metrics
      path: {{ .Values.monitoring.serviceMonitor.path }}
      interval: {{ .Values.monitoring.serviceMonitor.interval }}
      scrapeTimeout: {{ .Values.monitoring.serviceMonitor.scrapeTimeout }}
      {{- with .Values.monitoring.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.monitoring.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
