#!/bin/bash

OPERA_VERSION=$(opera --version)

cat <<_EOF
{
  "capabilities": [
    {
      "version": "$OPERA_VERSION",
      "browserName": "opera",
      "maxInstances": $NODE_MAX_INSTANCES,
      "seleniumProtocol": "WebDriver",
      "applicationName": "$NODE_APPLICATION_NAME"
    }
  ],
  "proxy": "org.openqa.grid.selenium.proxy.DefaultRemoteProxy",
  "maxSession": $NODE_MAX_SESSION,
  "host": "$NODE_HOST",
  "port": $NODE_PORT,
  "register": true,
  "registerCycle": $NODE_REGISTER_CYCLE,
  "nodePolling": $NODE_POLLING,
  "unregisterIfStillDownAfter": $NODE_UNREGISTER_IF_STILL_DOWN_AFTER,
  "downPollingLimit": $NODE_DOWN_POLLING_LIMIT
}
_EOF