; Documentation of this file format -> http://supervisord.org/configuration.html

; Priority 5 - selenium-kubernetes

[program:selenium-grid-kubernetes]
priority=5
command=/opt/bin/start-selenium-grid-kubernetes.sh
autostart=true
autorestart=false
startsecs=0
startretries=0

;Logs (all activity redirected to stdout so it can be seen through "kubectl logs")
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
