apiVersion: v1
kind: PersistentVolume
metadata:
  name: selenium-assets
  labels:
    app: selenium
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /tmp/selenium/assets
    type: DirectoryOrCreate
  storageClassName: ""
  persistentVolumeReclaimPolicy: Retain
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: selenium-assets
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 5Gi
  storageClassName: ""
  volumeName: selenium-assets
