apiVersion: v1
kind: ServiceAccount
metadata:
  name: selenium-node
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: selenium-node-role
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "delete", "get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["pods/log"]
    verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: selenium-node-rolebinding
subjects:
  - kind: ServiceAccount
    name: selenium-node
roleRef:
  kind: Role
  name: selenium-node-role
  apiGroup: rbac.authorization.k8s.io
