#!/bin/bash
set -e
# Run this with USER root only
for d in "$@"; do
    find "${d}" \
        ! \( \
            -group "${SEL_GID}" \
            -a -perm -g+rwX \
        \) \
        -exec chgrp -R "${SEL_GID}" -- {} \+ \
        -exec chmod -R g+rwX -- {} \+
    # setuid, setgid *on directories only*
    find "${d}" \
        \( \
            -type d \
            -a ! -perm -6000 \
        \) \
        -exec chmod -R +6000 -- {} \+
    # Relaxing permissions for OpenShift and other non-sudo environments
    chmod -R u+x "${d}"
    chgrp -R 0 "${d}"
    chmod -R g=u "${d}"
done
