#!/usr/bin/env bash
export HUB_LOG="/tmp/sel-hub.log"

sudo -E -i -u user1 \
  DOCKER_HOST_IP=$DOCKER_HOST_IP \
  java -jar /opt/selenium/selenium-server-standalone.jar -port $SELENIUM_PORT -role hub >>$HUB_LOG 2>&1
